# Generated by Django 2.2.4 on 2020-04-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_admin', '0003_restauranttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantmodel',
            fields=[
                ('restro_id', models.AutoField(primary_key=True, serialize=False)),
                ('restro_name', models.CharField(max_length=40, unique=True)),
                ('restro_contact_no', models.IntegerField(unique=True)),
                ('restro_email', models.EmailField(max_length=254, unique=True)),
                ('restro_password', models.CharField(max_length=20)),
                ('restro_otp', models.IntegerField()),
                ('restro_status', models.CharField(max_length=20)),
                ('restro_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.Areamodel')),
                ('restro_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.RestaurantType')),
            ],
        ),
    ]
